// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace OpenWeatherMapApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Clouds
    /// </summary>
    public partial class Clouds
    {
        /// <summary>
        /// Initializes a new instance of the Clouds class.
        /// </summary>
        public Clouds()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Clouds class.
        /// </summary>
        /// <param name="all">Cloudiness, %</param>
        public Clouds(int? all = default(int?))
        {
            All = all;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets cloudiness, %
        /// </summary>
        [JsonProperty(PropertyName = "all")]
        public int? All { get; set; }

    }
}
