// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace OpenWeatherMapApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Coord
    /// </summary>
    public partial class Coord
    {
        /// <summary>
        /// Initializes a new instance of the Coord class.
        /// </summary>
        public Coord()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Coord class.
        /// </summary>
        /// <param name="lon">City geo location, longitude</param>
        /// <param name="lat">City geo location, latitude</param>
        public Coord(double? lon = default(double?), double? lat = default(double?))
        {
            Lon = lon;
            Lat = lat;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets city geo location, longitude
        /// </summary>
        [JsonProperty(PropertyName = "lon")]
        public double? Lon { get; set; }

        /// <summary>
        /// Gets or sets city geo location, latitude
        /// </summary>
        [JsonProperty(PropertyName = "lat")]
        public double? Lat { get; set; }

    }
}
