// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace OpenWeatherMapApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Wind
    /// </summary>
    public partial class Wind
    {
        /// <summary>
        /// Initializes a new instance of the Wind class.
        /// </summary>
        public Wind()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Wind class.
        /// </summary>
        /// <param name="speed">Wind speed. Unit Default: meter/sec, Metric:
        /// meter/sec, Imperial: miles/hour.</param>
        /// <param name="deg">Wind direction, degrees (meteorological)</param>
        public Wind(double? speed = default(double?), int? deg = default(int?))
        {
            Speed = speed;
            Deg = deg;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets wind speed. Unit Default: meter/sec, Metric:
        /// meter/sec, Imperial: miles/hour.
        /// </summary>
        [JsonProperty(PropertyName = "speed")]
        public double? Speed { get; set; }

        /// <summary>
        /// Gets or sets wind direction, degrees (meteorological)
        /// </summary>
        [JsonProperty(PropertyName = "deg")]
        public int? Deg { get; set; }

    }
}
